services:
  auto-twi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./ss:/app/ss
    environment:
      - proxy=${proxy:-}

    ports:
      - "8000:8000"

    restart: always
