services:
  auto-twi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./ss:/app/ss
      - ./data:/app/data
    environment:
      - proxy=${proxy:-}
    init: true

    ports:
      - "8000:8000"

    restart: always
